<a href="https://colab.research.google.com/github/cagatayogretmen/nlp-tools/blob/master/numpy_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#NUMPY SATIR ÖNCELİĞİ

a = [1,2,3]
b = [4,5,6]
a
b #böyle bir durumda en son satır çalışır. yani sadece b dikkate alındı 

In [2]:
#NUMPY ARRAY OLUŞTURMA

import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])

type(a) 

a*b #numpy matris çarpımını kolayca yapmamızı sağlar
#numpy pythonun listelerindeki her değer için değer tutmasına karşın bir arrayde genel bir bilgi tutar, bu yüzden hızlıdır, az yer harcar

array([ 4, 10, 18])

In [5]:
#ELEMANLARI İÇİN SABİT BİLGİ TUTMA

a = np.array([1, 2.3, 4, 5.6]) #numpy elemanları sabit şekle sokar o yüzden hepsini floata çevirdi

b = np.array([1, 2.3, 4], dtype="int") #elemanların biçimini int belirledik

array([1, 2, 4])

In [0]:
#OTOMATİK MATRİSLER OLUŞTURMA

a = np.zeros(10, dtype=int)
b = np.ones((3,5) dtype=int) #3 satır 5 sütunluk tüm elemanları 1 olan matris
c = np.full((3,5), 8) #3 satır 5 sütunluk tüm elemanları 8 olan matrix
d = np.arange(0, 31, 3) #0'dan 31'e kadar 3er 3er artan dizi
e = np.linspace(0,1,10) #0 ile 1 arasında 10 elemanları matrix
f = np.random.normal(10, 4, (3,5)) #ortalaması 10 s.s'si 4 3,5 lik matris 
g = np.random.randint(0,10, (3,5)) #3e 5lik 0 10 arası rastgele değer almış matrix 
#tek boyutlu array:vektör
#iki boyutlu vektör:matris



In [3]:
#TEK BOYUTLU ARRAY İŞLEMLERİ

a = np.random.randint(10, size=10) #0-10 arası size:eleman sayısı
a.ndim #dimension:kaç boyutlu olduğunu gösterir : 1 döndürür
a.shape #boyut bilgisi verir :(10, ) döndürür
a.size #içindeki toplam eleman sayısı :10 döndürür
a.dtype #arrayin içindeki elemanların tipini verir: int64 döndürür

#İKİ BOYUTLU ARRAY İŞLEMLERİ

b = np.random.randint(10, size=(3,5))
b.ndim #2 boyutludur
b.shape #(3,5)
b.size # 15:toplam eleman sayısı

2

In [0]:
#RESHAPING(YENİDEN BİÇİMLENDİRME)

a = np.arange(1,10)
print(a)
b = a.reshape((3,3))
print(b)

#a tek boyutlu bir vektördür fakat bunu matrise çevirebiliriz
c = a.reshape((1,9)) #köşeli parentez 2 adet olur çünkü boyutu 2ye çıktı
print('cnin boyutu:',c.ndim)
print(c)



In [0]:
#CONCENATION(BİRLEŞTİRME)

a = np.array([1,2,3])
b = np.array(['x','y','z'])

c = np.concatenate([a,b])

#2 BOYUTTA BİRLEŞTİRME

a = np.array([[1,2,3], 
              [4,5,6]])

d = np.concatenate([a,a]) #satır bazında alta doğru birleştirir çünkü default axis = 0 parametrelidir
print(d) 

e = np.concatenate([a,a], axis=1) #yana doğru yandan sütunsal birleştirme yapar
print(e)

In [0]:
#SPLITTING(ARRAY AYIRMA)

x =np.array([1,2,3,4,5,6,7,8])

y = np.split(x, [3,6]) #3.elemana ve 6.elemana kadar x arrayini ayır
print(y)

a,b,c = np.split(x, [3,6]) #böylece a,b,c ye böldüğümüz arrayleri atadık)

#2 BOYUTLU AYIRMA

m = np.arange(16).reshape(4,4)
print('m:', m)

#VSPLIT(satırsal bölme) 
np.vsplit(m, [3]) #3.satır elemanından sonrayı böl

ust,alt = np.vsplit(m, [3])

print('ust:',ust)
print('alt:',alt)

#HSPLIT(sütunsal bölme)

sag, sol = np.hsplit(m, [2])
print('sol:',sag)
print('sag:',sol)



In [0]:
#SORTING(SIRALAMA)

v = np.array([1,5,3,2,9,5,1,5])

np.sort(v)

v.sort() #python gömülü fonksiyonu numpy değil yapısını bozar

m = np.random.normal(20,5, (3,3))
print(m)
a = np.sort(m, axis=1) # her satırı kendi içinde sıralamış
print(a)
b = np.sort(m, axis=0) #her sütunu kendi içinde sıralamış
print(b)



In [0]:
#INDEX İŞLEMLERİ

m = np.random.randint(20, size=(3,6))
print(m)

m[2,0]
m[2,4] = 20

print(m)

m[2,4] = 20.89 #20 olarak değiştirir çünkü arrayin yapısı int di
#!eğer en başta 20.89 içeren değerimiz olsaydı tüm array float tipinde olacaktı
print(m)



In [64]:
#SLICING

#TEK BOYUTLU

a = np.arange(20,30)
print(a)

a[0::3] #0.indexden başlayıp 3er 3er gider

#2 BOYUTLU

m = np.random.randint(10, size=(5,5))
print(m)

m[:,0] #m[satır aralığı, sütun aralığı] :[tüm satırlar, 0.sütun]
m[2, :] #satır seçtik

m[0:2, 1:3]

[20 21 22 23 24 25 26 27 28 29]
[[2 3 3 4 6]
 [5 9 6 2 4]
 [6 8 2 2 6]
 [6 6 0 6 1]
 [0 4 2 0 2]]


array([[3],
       [9]])

In [0]:
#ALT KÜME ÜZERİNDE İŞLEM YAPMAK

#arrayların alt kümeleri üzerinde yaptığımız işlemler farklı değişkene kaydolsa da ana arrayin elemanlarını değiştirir

a = np.random.randint(10, size = (5,5))

alt_kume = a[0:3, 1:3]

alt_kume[1,1] = 90
alt_kume[0,1] = 30 #bu değişilkleri alt_kume ye yapmamıza rağmen a arrayının elemanlarını değiştirdi


alt_kume_2 = a[0:3, 1:3].copy() #böylece işlemler sadece bu array için olacaktır

In [19]:
#FANCY INDEX İLE ELEMANLARA ERİŞMEK

v = np.arange(0,30,3)

v[1]
v[5]
v[7] #gibi v vektörünün elemanlarına erişiyoruz. bu erişmeleri toplu olarak otomatikçe fancy index ile yaparız

al_getir = [1,5,7]

v[al_getir] #ile hepsini getirir


#2 BOYUTLU MATRİXTE FANCY INDEX

m = np.arange(9).reshape((3,3))
print(m)

satir = np.array([0,1])
sutun = np.array([1,2])

m[satir, sutun]

#slice ile fancy

m[0:, [1,2]]


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [22]:
#KOŞULLUR ELEMAN İŞLEMLERİ

v = np.array([1,2,3,4,5])

print(v<5) #v nin elemanlarını koşula göre true false döndürür

#sorguyu sağlayan değerleri alma

v[v<3]

v[v!=2] #2nin dışında kalanları getir

[ True  True  True  True False]


array([1, 3, 4, 5])

In [35]:
#MATEMATİKSEL İŞLEMLER

v = np.array([1,2,3,4,5,6,7])

v*3 #tüm elemanları 3 ile çarpar
v/3 #tüm elemanları 3 ile böler

np.divide(v,3) #aslında arkada çalışan fonksiyonlar hep böyledir
np.multiply(v,2) #çarpma
np.power(v,4) #tüm elemanların 4.dereceden kuvvetini alır
np.mod(v,2) #tüm elemanların 2 ye böümünden kalan sayıdır

#trigonometrik işlemler

np.sin(360)
np.cos(180)

#logaritma
np.log2(v)

#aramalar yaparken cheat sheet olarak aramak avantajlı

#istatistik

np.mean(v)
np.sum(v)
np.min(v)
np.max(v)

7

In [39]:
#İKİ BİLİNMEYENLİ DENKLEM ÇÖZME

# 2.x1 + 3.x2 = 18
# 4.x1 + 5.x2 = 32 denklemini çözecez 

a = np.array([[2,3], [4,5]])
b = np.array([18,32])

x = np.linalg.solve(a,b)
print(x)



array([3., 4.])